### ISSUE TITLE
Misspelling on the Expense Action Menu

### ISSUE THREAD

**Issue by JessecaCasanare** [rydoo/translations-Typos#9] opened 2019-01-23 07:15 UTC
![snipaste_2019-01-23_13-48-00](https://user-images.githubusercontent.com/45615763/51589376-b86c5500-1f21-11e9-8cba-b94987cbed02.png)

**Comment by sebastiaanvanhecke** [comment] 2019-01-23 08:01
thanks @JessecaCasanare 
the issue is known and will be fixed soon. thanks for posting !

**Closed by sebastiaanvanhecke** 2019-01-23 08:01 UTC
